config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    get 'my_portfolio' , to: 'users#my_portfolio'
    resources :users, only: [:show]
  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'search_stock' , to: 'stocks#search'
   
  get 'friends' , to: 'friendship#index'
  get 'search_friend' , to: 'friendship#search'
  resources :friendship

  # get 'search_stock' , to: 'stocks#search', :defaults => { :format => 'js' }
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'


end

app/models/stock.rb
class Stock < ApplicationRecord


    has_many :user_stocks
    has_many :stocks, through: :user_stocks 

    validates :ticker, :name , presence: true

    def self.new_lookup(name)
        client = IEX::Api::Client.new(
            publishable_token: 'pk_3d6bbacde6f64f2abd5c868cee872eb1',
            secret_token:  "sk_233cdd40821948d0b76b69e927b9fcb3",
            endpoint: 'https://cloud.iexapis.com/v1'
          )
            # client.price(name)    
        begin
            new(ticker: name, name: client.company(name).company_name, last_price:  client.price(name))
        rescue => exception
            nil 
        end
    end

    def self.check_db(ticker)
        Stock.where(ticker: ticker).first
      
    end
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    has_many :user_stocks
    has_many :stocks, through: :user_stocks
    has_many :friendships
    has_many :friends , through: :friendships

    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

    def full_name
      return "#{first_name} #{last_name}" if first_name || last_name

      "anonyomous"
      
    end
    
    def self.search_user(param)
      param.strip!
      to_send_back = (search_first_name(param)+search_last_name(param) + search_email(param)).uniq
      return nil unless to_send_back
      to_send_back  
    end

    def self.search_first_name(param)
      matches('first_name',param)
    end
   
    def self.search_last_name(param)
      
      matches('last_name',param)

    end
   
    def self.search_email(param)
      
      matches('email',param)

    end
   
    def self.check_db_user(friend)
      User.where(first_name: friend).first
    end

    def self.matches(field_name,param)
    where("#{field_name} like?", "%#{param}%")
      
    end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

        before_action :configure_permitted_parameters, if: :devise_controller?
      
        protected
      
        def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:account_update, keys: [:first_name , :last_name])
        end
        def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name , :last_name])
        end
  
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController
    before_action :set_friends
    def index
        # @friends = current_user.friends
    end

    def search

        # @friend = User.where(first_name: params[:friend]).first
        @the_friends = User.search_user(params[:friend])
        # debugger
        if @the_friends 
          
            render :index
        else
            flash[:alert] = "Please enter a valid user name"
            redirect_to friendship_index_path
        end

    end

    def create
        
        friend = User.check_db_user(params[:friend])
        
        if !current_user.friends.where(id:friend.id).exists?
        @user_friend = Friendship.create(user: current_user, friend: friend)
        flash[:notice] = " #{friend.first_name} is successfully added to your account"

        redirect_to friendship_index_path
        
         end

    end

    def destroy
        friend = User.find(params[:id])
        user_friend = Friendship.where(user_id: current_user.id,friend_id: friend.id).first
        user_friend.destroy 
        redirect_to friendship_index_path

    end


    private

    def set_friends
        @friends = current_user.friends
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to "/my_portfolio"
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
     def search
    
      @stock = Stock.new_lookup(params[:stock])
      @track_stock = current_user.stocks
      # render json: stock
      if params[:stock].present?
         if @stock

        return render 'users/my_portfolio'
         else 
          flash[:alert] = "Please enter a valid symbol"
          redirect_to my_portfolio_path
        end

      else
        flash[:alert] = "please enter a symbol to search"
        redirect_to my_portfolio_path
      end
    end

    def result  

     end
end
  

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
        stock = Stock.new_lookup(params[:ticker])
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} is successfully added to your portfolio"
        redirect_to my_portfolio_path
    end
    def destroy
       stock = Stock.find(params[:id])
       user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
       user_stock.destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @track_stock = current_user.stocks
    
  end
  def show
   @user = User.find( params[:id])
   @user_stock = User
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendship/_search.html.erb
<% if @friend %>
<div class="card mb-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @friend.first_name %></h5>
    <p class="card-text"><strong>NAME:</strong><%= @friend.email%></p>
    <p class="card-text"><strong>PRICE:</strong><%= @stock.last_price%></p>
    <%= button_to 'ADD TO YOUR PORTFOLIO',user_stocks_path(user: current_user, ticker: @stock.ticker) , class: "btn btn-success", method: :post %>
  </div>
</div>
<% end %>

app/views/friendship/index.html.erb
<div class="mt-5">
<h3>Search Friends</h3>
    <%= form_tag search_friend_path,remote: :ture, method: :get do %>
   <div class= "form-group row">
    <div class="col-sm-11 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Searh for friends", autofocus: true, class: "form-control form-control-large"%>
    </div>
    <div class="col-sm-1 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
       <%= fa_icon 'search 1.8x'%>
        <% end %>
    </div>
   </div>
    <% end %>
</div>

<% if @the_friends %>
 <% @the_friends.each do |friendss| %>
  
     <div class="div-for-friend-result">
    
        <h5 class=""><%= friendss.first_name %> <%= friendss.last_name %></h5>
        <p class=""><strong>Email:</strong><%= friendss.email%></p>
        <p class=""><%= link_to "View Profile" , user_path(id: friendss.id)%></p>
    
        <% if !current_user.friends.where(id:friendss.id).exists? %>
        <%= button_to 'ADD TO YOUR FRIEND',friendship_index_path(user: current_user, friend: friendss.first_name) , class: "btn btn-success", method: :post %>
        <% else %>
        <span class="badge badge-secondary">Already friends</span>
        <% end %>
    
</div>



   
 <% end %>
<% end %>




<div class="row mt-4" >
    <div class= "col-12">
        <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |friend| %>
                <tr>
                <th scope="row"><%= friend.first_name %> <%= friend.last_name %></th>
                <td><%= friend.email  %></td>
                <td style="display:flex">
                    <button class="mr-3 primary-btn btn"><%= link_to "View Profile" , user_path(id: friend.id)%></button>
    
                    <%= button_to 'Unfriend',friendship_path(friend.id),method: :delete, data: { turbo_confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success mt-3'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger mt-3'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <%= link_to "Finance Tracker" ,root_path , class:"navbar-brand" %>
  <% if current_user %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to "Portfolio", my_portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == friends_path %>">
          <%= link_to "My Friends", friends_path, class: "nav-link" %>
        </li>
               
        
      </ul>
      <ul class= "navbar-nav ml-auto">
      <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </a>
          <div class="dropdown-menu">
            <%= link_to  edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon 'edit'%> Edit Account
            <% end %>
            
          </div>
        </li>
        <li>
          <%= button_to  "Logout" , destroy_user_session_path, method: :delete, class: " btn btn-danger mr-3" %>    
        </li>
      </ul>
 <% end %> 
    </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance Tracker Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_result.html.erb
<% if @stock %>
<div class="card mb-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @stock.ticker %></h5>
    <p class="card-text"><strong>NAME:</strong><%= @stock.name%></p>
    <p class="card-text"><strong>PRICE:</strong><%= @stock.last_price%></p>
    <%= button_to 'ADD TO YOUR PORTFOLIO',user_stocks_path(user: current_user, ticker: @stock.ticker) , class: "btn btn-success", method: :post %>
  </div>
</div>
<% end %>

app/views/users/my_portfolio.html.erb
<div class="mt-5">
<h3>Search Stocks</h3>
    <%= form_tag search_stock_path,remote: true , method: :get do %>
   <div class= "form-group row">
    <div class="col-sm-11 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, class: "form-control form-control-large"%>
    </div>
    <div class="col-sm-1 no-left-padding">
        <%= button_tag type: :submit,remote: true, class: "btn btn-success" do %>
       <%= fa_icon 'search 1.8x'%>
        <% end %>
    </div>
   </div>
    <% end %>
</div>
  
  <%= render 'users/result'%>

  
<% if !@track_stock.empty? %>
 <div class="row">
    <div class= "col-12">
        <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Last Price</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @track_stock.each do |stocks| %>
                <tr>
                <th scope="row"><%= stocks.ticker %></th>
                <td><%= stocks.name %></td>
                <td><%= stocks.last_price %></td>
                 <td><%= button_to 'destroy',user_stock_path(stocks),method: :delete, class: "btn btn-danger" %></td>

                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<% if !@user_stock.empty? %>
 <div class="row">
    <div class= "col-9">
        <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Last Price</th>
            <%# <th scope="col">Action</th> %>
            </tr>
        </thead>
        <tbody>
            <% @user_stock.each do |stocks| %>
                <tr>
                <th scope="row"><%= stocks.ticker %></th>
                <td><%= stocks.name %></td>
                <td><%= stocks.last_price %></td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>
<% else %>
<h1><%= @user.first_name %> dont follow any stocks
<% end %>